language: java
jdk: openjdk11
services:
  - docker

before_install:
  - mkdir -p $HOME/.gradle
  - touch $HOME/.gradle/gradle.properties

env:
  matrix:
    - VERSIONS_TO_BUILD=4
    - VERSIONS_TO_BUILD=5
    - VERSIONS_TO_BUILD=6

install:
  - "echo 'buildDate='$(date +%s) >> ~/.gradle/gradle.properties"

script: travis_wait 60 ./gradlew -PrepoName=docker.io/xenit buildDockerImage --info

deploy:
  provider: script
  script: ./gradlew --stacktrace -PrepoName=docker.io/xenit pushDockerImage
  cleanup: false
  on:
    branch: master
