language: java
jdk: openjdk11
services:
  - docker

before_install:
  - mkdir -p $HOME/.gradle
  - touch $HOME/.gradle/gradle.properties

install:
  - "echo 'buildDate='$(date +%s) >> ~/.gradle/gradle.properties"

script: travis_wait 60 ./gradlew -PrepoName=docker.io/xenit buildDockerImage --info

deploy:
  provider: script
  script: ./gradlew --stacktrace -PrepoName=docker.io/xenit pushDockerImage
  skip_cleanup: true
  cleanup: false
  on:
    branch: master
