ARG BASE_IMAGE=xeniteu/tomcat:alfresco-6.0-ubuntu
FROM $BASE_IMAGE

ARG SHARE_VERSION_MAJOR
ARG SHARE_VERSION_MINOR
ARG SHARE_VERSION_REV
ARG SHARE_FLAVOR

# ${CATALINA_HOME} is set to ${CATALINA_HOME} in upstream

# download location alf
ENV SHARE_VERSION ${SHARE_VERSION_MAJOR}.${SHARE_VERSION_MINOR}.${SHARE_VERSION_REV}
ENV SHARE_FLAVOR ${SHARE_FLAVOR}

USER	root

RUN	mkdir -p /opt/alfresco && \
	apt-get update && \
	apt-get install -y curl vim locate jq less && \
	rm -rf ${CATALINA_HOME}/webapps/* && \
	mkdir -p ${CATALINA_HOME}/bin && \
	touch ${CATALINA_HOME}/bin/setenv.sh && \
 	mkdir -p ${CATALINA_HOME}/shared/classes/alfresco/web-extension/
ADD 	share-config-custom.xml ${CATALINA_HOME}/shared/classes/alfresco/web-extension/

# copy init file
RUN	mkdir -p /docker-entrypoint.d
COPY 	91-init-share.sh /docker-entrypoint.d/
RUN	chmod u+x /docker-entrypoint.d/91-init-share.sh && \
	
# permissions
 	chown -hR tomcat /opt/alfresco && \
	chown -hR tomcat ${CATALINA_HOME} 

# named volumes
VOLUME 	${CATALINA_HOME}/temp ${CATALINA_HOME}/logs

WORKDIR /opt/alfresco

HEALTHCHECK --interval=10s --timeout=3s --retries=3 --start-period=20s CMD curl -f http://localhost:${TOMCAT_PORT}/share || exit 1

# start ALF will be done by java image's entrypoint + tomcat image's CMD
